### ISSUE TITLE
how to evaluate GaC？

### ISSUE THREAD

**Issue by LianShuQuan** [yaoching0/GaC#3]
hello！
Did you use lm-eval to evaluate GaC？What‘s the command？Otherwise how did you evaluate GaC？

**Comment by yaoching0** [comment]
Sorry for the late reply! I will outline the steps below to reproduce the evaluation from the paper～

### Follow these steps for evaluation:

1. Install `lm-eval-harness` from this commit:
   [https://github.com/EleutherAI/lm-evaluation-harness/tree/9e6e240229429d2214bc281bed7a4e288f5169a1](https://github.com/EleutherAI/lm-evaluation-harness/tree/9e6e240229429d2214bc281bed7a4e288f5169a1)
   
2. In the `lm-evaluation-harness/lm_eval/models` directory, create a new file `GaC.py`, and insert the following content:
   ```python
    from typing import List

    import requests as rq

    from lm_eval.api.instance import Instance
    from lm_eval.api.model import LM
    from lm_eval.api.registry import register_model
    from tqdm import tqdm

    @register_model("GaC")
    class GaCLM(LM):
        def __init__(self, *args, **kwargs):
            super().__init__()
            self.batch_size = int(kwargs.get("batch_size"))
            self.api_url = "http://0.0.0.0:8000/api/generate/" # GaC server

        def generate_until(self, requests: List[Instance]) -> List[str]:
            print(f"total num of samples: {len(requests)} with bs {self.batch_size}")
            final_texts = []

            for i in tqdm(
                range(0, len(requests), self.batch_size), desc="Generating response..."
            ):
                batch_requests = requests[i : i + self.batch_size]
                messages_list = [
                    [{"role": "user", "content": request.args[0]}]
                    for request in batch_requests
                ]
                max_gen_toks = max(
                    request.args[1].get("max_gen_toks", 400) for request in batch_requests
                )
                untils = [request.args[1].get("until", None) for request in batch_requests]

                data = {
                    "messages_list": messages_list,
                    "max_new_tokens": max_gen_toks,
                    "until": untils[0],
                }

                response = rq.post(self.api_url, json=data)
                if response.status_code == 200:
                    generated_texts_batch = response.json().get("response", [])

                    for j, generated_text in enumerate(generated_texts_batch):
                        # input_text = batch_requests[j].args[0]
                        until = untils[j]
                        if until:
                            for term in until:
                                if term in generated_text:
                                    generated_text = generated_text.split(term)[0]
                                    break
                        final_text = generated_text  # input_text + generated_text
                        final_texts.append(final_text)
                else:
                    raise Exception(
                        f"API call failed with status code {response.status_code}: {response.text}"
                    )

            return final_texts

        def loglikelihood(self, requests: list[Instance]) -> list[tuple[float, bool]]:
            raise NotImplementedError()

        def loglikelihood_rolling(
            self, requests: list[Instance]
        ) -> list[tuple[float, bool]]:
            raise NotImplementedError()
   ```
   
3. Add `import GaC` to `lm-evaluation-harness/lm_eval/models/__init__.py`.

4. Refer to the [README](https://github.com/yaoching0/GaC/tree/main) to install and start the GaC server.

5. Run the `lm_eval` command to execute the evaluation.

### The lm-eval-harness tasks tested in our paper are:
- `mmlu_flan_n_shot_generative`, 5-shots
- `gsm8k`, 5-shots
- `bbh_fewshot`, 3-shots
- `triviaqa`, 5-shots
- `nq_open`, 5-shots

### Example command to run:
```
lm_eval --model GaC --tasks mmlu_flan_n_shot_generative --batch_size 1 --num_fewshot 5
```
You can replace `tasks` with any of the tasks listed above. For `bbh_fewshot`, we applied an additional filter. See details below.

### bbh_fewshot

If you want to run `bbh_fewshot`, please make the following changes; otherwise, you can skip this section:

1. Add a file `utils.py` under `lm-evaluation-harness/lm_eval/tasks/bbh/fewshot` with the following content:
   ```python
    from lm_eval.filters.extraction import RegexFilter


    class MultiChoiceRegexFilter(RegexFilter):
        """ """

        def __init__(
            self,
            regex_pattern: str = r"#### (\-?[0-9\.\,]+)",
            group_select=0,
            fallback: str = "[invalid]",
            ignore_case=False,
            ignore_punctuation=False,
            regexes_to_ignore=None,
        ) -> None:
            """
            regex_pattern: The basic regex pattern to use. If fails to match, we will use the customized match procedure
                            - step 1 : We parse the choices between ([A-Z])s then try to find these choices in the response.
                            - step 2 : We parse the choice with regex :[\s]*([A-?]), where ? varies by number of choices.
            group_select: Selects the (group_select)th match from the findall result.
            ignore_case: Ignores the case during step 1 matching
            ignore_punctuation: Remove the punctuation during step 1 matching
            regexes_to_ignore: Remove these regexes during step 1 matching
            """
            super().__init__(regex_pattern, group_select, fallback)
            self.ignore_case = ignore_case
            self.ignore_punctuation = ignore_punctuation
            self.regexes_to_ignore = regexes_to_ignore
   ```
   
2. In `lm-evaluation-harness/lm_eval/tasks/bbh/fewshot/_fewshot_template_yaml`, add:
   ```yaml
   filter_list:
     - name: "strict-match"
       filter:
         - function: "take_first"
     - name: "flexible-extract"
       filter:
         - function: !function utils.MultiChoiceRegexFilter
           group_select: 0
           regex_pattern: "^\\s*(.+?)(?=(\\n+|$))"
           ignore_case: true
           ignore_punctuation: true
         - function: "take_first"
   ```
   
3. Run the `lm_eval` command. Example:
   ```
   lm_eval --model GaC --tasks bbh_fewshot --batch_size 1 --num_fewshot 3
   ```

Feel free to reach out if you have any questions!

**Comment by yaoching0** [comment]
> hello！ Did you use lm-eval to evaluate GaC？What‘s the command？Otherwise how did you evaluate GaC？

Sorry for the late reply! I will outline the steps below to reproduce the evaluation from [our paper](https://arxiv.org/abs/2406.12585)～

### Follow these steps for evaluation:

1. Install `lm-eval-harness` from this commit:
   [https://github.com/EleutherAI/lm-evaluation-harness/tree/9e6e240229429d2214bc281bed7a4e288f5169a1](https://github.com/EleutherAI/lm-evaluation-harness/tree/9e6e240229429d2214bc281bed7a4e288f5169a1)
   
2. In the `lm-evaluation-harness/lm_eval/models` directory, create a new file `GaC.py`, and insert the following content:
   ```python
    from typing import List

    import requests as rq

    from lm_eval.api.instance import Instance
    from lm_eval.api.model import LM
    from lm_eval.api.registry import register_model
    from tqdm import tqdm

    @register_model("GaC")
    class GaCLM(LM):
        def __init__(self, *args, **kwargs):
            super().__init__()
            self.batch_size = int(kwargs.get("batch_size"))
            self.api_url = "http://0.0.0.0:8000/api/generate/" # GaC server

        def generate_until(self, requests: List[Instance]) -> List[str]:
            print(f"total num of samples: {len(requests)} with bs {self.batch_size}")
            final_texts = []

            for i in tqdm(
                range(0, len(requests), self.batch_size), desc="Generating response..."
            ):
                batch_requests = requests[i : i + self.batch_size]
                messages_list = [
                    [{"role": "user", "content": request.args[0]}]
                    for request in batch_requests
                ]
                max_gen_toks = max(
                    request.args[1].get("max_gen_toks", 400) for request in batch_requests
                )
                untils = [request.args[1].get("until", None) for request in batch_requests]

                data = {
                    "messages_list": messages_list,
                    "max_new_tokens": max_gen_toks,
                    "until": untils[0],
                }

                response = rq.post(self.api_url, json=data)
                if response.status_code == 200:
                    generated_texts_batch = response.json().get("response", [])

                    for j, generated_text in enumerate(generated_texts_batch):
                        # input_text = batch_requests[j].args[0]
                        until = untils[j]
                        if until:
                            for term in until:
                                if term in generated_text:
                                    generated_text = generated_text.split(term)[0]
                                    break
                        final_text = generated_text  # input_text + generated_text
                        final_texts.append(final_text)
                else:
                    raise Exception(
                        f"API call failed with status code {response.status_code}: {response.text}"
                    )

            return final_texts

        def loglikelihood(self, requests: list[Instance]) -> list[tuple[float, bool]]:
            raise NotImplementedError()

        def loglikelihood_rolling(
            self, requests: list[Instance]
        ) -> list[tuple[float, bool]]:
            raise NotImplementedError()
   ```
   
3. Add `from . import GaC` to `lm-evaluation-harness/lm_eval/models/__init__.py`.

4. Refer to the [README](https://github.com/yaoching0/GaC/tree/main) to install and start the GaC server.

5. Run the `lm_eval` command to execute the evaluation.

### The lm-eval-harness tasks tested in our paper are:
- `mmlu_flan_n_shot_generative`, 5-shots
- `gsm8k`, 5-shots
- `bbh_fewshot`, 3-shots
- `triviaqa`, 5-shots
- `nq_open`, 5-shots

### Example command to run:
```
lm_eval --model GaC --tasks mmlu_flan_n_shot_generative --batch_size 1 --num_fewshot 5
```
You can replace `tasks` with any of the tasks listed above. For `bbh_fewshot`, we applied an additional filter. See details below.

### bbh_fewshot

If you want to run `bbh_fewshot`, please make the following changes; otherwise, you can skip this section:

1. Add a file `utils.py` under `lm-evaluation-harness/lm_eval/tasks/bbh/fewshot` with the following content:
   ```python
    from lm_eval.filters.extraction import RegexFilter


    class MultiChoiceRegexFilter(RegexFilter):
        """ """

        def __init__(
            self,
            regex_pattern: str = r"#### (\-?[0-9\.\,]+)",
            group_select=0,
            fallback: str = "[invalid]",
            ignore_case=False,
            ignore_punctuation=False,
            regexes_to_ignore=None,
        ) -> None:
            """
            regex_pattern: The basic regex pattern to use. If fails to match, we will use the customized match procedure
                            - step 1 : We parse the choices between ([A-Z])s then try to find these choices in the response.
                            - step 2 : We parse the choice with regex :[\s]*([A-?]), where ? varies by number of choices.
            group_select: Selects the (group_select)th match from the findall result.
            ignore_case: Ignores the case during step 1 matching
            ignore_punctuation: Remove the punctuation during step 1 matching
            regexes_to_ignore: Remove these regexes during step 1 matching
            """
            super().__init__(regex_pattern, group_select, fallback)
            self.ignore_case = ignore_case
            self.ignore_punctuation = ignore_punctuation
            self.regexes_to_ignore = regexes_to_ignore
   ```
   
2. In `lm-evaluation-harness/lm_eval/tasks/bbh/fewshot/_fewshot_template_yaml`, add:
   ```yaml
   filter_list:
     - name: "strict-match"
       filter:
         - function: "take_first"
     - name: "flexible-extract"
       filter:
         - function: !function utils.MultiChoiceRegexFilter
           group_select: 0
           regex_pattern: "^\\s*(.+?)(?=(\\n+|$))"
           ignore_case: true
           ignore_punctuation: true
         - function: "take_first"
   ```
   
3. Run the `lm_eval` command. Example:
   ```
   lm_eval --model GaC --tasks bbh_fewshot --batch_size 1 --num_fewshot 3
   ```

Feel free to reach out if you have any questions!

**Comment by LianShuQuan** [comment]
thank you

> > hello！ Did you use lm-eval to evaluate GaC？What‘s the command？Otherwise how did you evaluate GaC？
> 
> Sorry for the late reply! I will outline the steps below to reproduce the evaluation from [our paper](https://arxiv.org/abs/2406.12585)～
> 
> ### Follow these steps for evaluation:
> 1. Install `lm-eval-harness` from this commit:
>    https://github.com/EleutherAI/lm-evaluation-harness/tree/9e6e240229429d2214bc281bed7a4e288f5169a1
> 2. In the `lm-evaluation-harness/lm_eval/models` directory, create a new file `GaC.py`, and insert the following content:
>    ```python
>     from typing import List
>    
>     import requests as rq
>    
>     from lm_eval.api.instance import Instance
>     from lm_eval.api.model import LM
>     from lm_eval.api.registry import register_model
>     from tqdm import tqdm
>    
>     @register_model("GaC")
>     class GaCLM(LM):
>         def __init__(self, *args, **kwargs):
>             super().__init__()
>             self.batch_size = int(kwargs.get("batch_size"))
>             self.api_url = "http://0.0.0.0:8000/api/generate/" # GaC server
>    
>         def generate_until(self, requests: List[Instance]) -> List[str]:
>             print(f"total num of samples: {len(requests)} with bs {self.batch_size}")
>             final_texts = []
>    
>             for i in tqdm(
>                 range(0, len(requests), self.batch_size), desc="Generating response..."
>             ):
>                 batch_requests = requests[i : i + self.batch_size]
>                 messages_list = [
>                     [{"role": "user", "content": request.args[0]}]
>                     for request in batch_requests
>                 ]
>                 max_gen_toks = max(
>                     request.args[1].get("max_gen_toks", 400) for request in batch_requests
>                 )
>                 untils = [request.args[1].get("until", None) for request in batch_requests]
>    
>                 data = {
>                     "messages_list": messages_list,
>                     "max_new_tokens": max_gen_toks,
>                     "until": untils[0],
>                 }
>    
>                 response = rq.post(self.api_url, json=data)
>                 if response.status_code == 200:
>                     generated_texts_batch = response.json().get("response", [])
>    
>                     for j, generated_text in enumerate(generated_texts_batch):
>                         # input_text = batch_requests[j].args[0]
>                         until = untils[j]
>                         if until:
>                             for term in until:
>                                 if term in generated_text:
>                                     generated_text = generated_text.split(term)[0]
>                                     break
>                         final_text = generated_text  # input_text + generated_text
>                         final_texts.append(final_text)
>                 else:
>                     raise Exception(
>                         f"API call failed with status code {response.status_code}: {response.text}"
>                     )
>    
>             return final_texts
>    
>         def loglikelihood(self, requests: list[Instance]) -> list[tuple[float, bool]]:
>             raise NotImplementedError()
>    
>         def loglikelihood_rolling(
>             self, requests: list[Instance]
>         ) -> list[tuple[float, bool]]:
>             raise NotImplementedError()
>    ```
> 3. Add `from . import GaC` to `lm-evaluation-harness/lm_eval/models/__init__.py`.
> 4. Refer to the [README](https://github.com/yaoching0/GaC/tree/main) to install and start the GaC server.
> 5. Run the `lm_eval` command to execute the evaluation.
> 
> ### The lm-eval-harness tasks tested in our paper are:
> * `mmlu_flan_n_shot_generative`, 5-shots
> * `gsm8k`, 5-shots
> * `bbh_fewshot`, 3-shots
> * `triviaqa`, 5-shots
> * `nq_open`, 5-shots
> 
> ### Example command to run:
> ```
> lm_eval --model GaC --tasks mmlu_flan_n_shot_generative --batch_size 1 --num_fewshot 5
> ```
> 
> You can replace `tasks` with any of the tasks listed above. For `bbh_fewshot`, we applied an additional filter. See details below.
> 
> ### bbh_fewshot
> If you want to run `bbh_fewshot`, please make the following changes; otherwise, you can skip this section:
> 
> 1. Add a file `utils.py` under `lm-evaluation-harness/lm_eval/tasks/bbh/fewshot` with the following content:
>    ```python
>     from lm_eval.filters.extraction import RegexFilter
>    
>    
>     class MultiChoiceRegexFilter(RegexFilter):
>         """ """
>    
>         def __init__(
>             self,
>             regex_pattern: str = r"#### (\-?[0-9\.\,]+)",
>             group_select=0,
>             fallback: str = "[invalid]",
>             ignore_case=False,
>             ignore_punctuation=False,
>             regexes_to_ignore=None,
>         ) -> None:
>             """
>             regex_pattern: The basic regex pattern to use. If fails to match, we will use the customized match procedure
>                             - step 1 : We parse the choices between ([A-Z])s then try to find these choices in the response.
>                             - step 2 : We parse the choice with regex :[\s]*([A-?]), where ? varies by number of choices.
>             group_select: Selects the (group_select)th match from the findall result.
>             ignore_case: Ignores the case during step 1 matching
>             ignore_punctuation: Remove the punctuation during step 1 matching
>             regexes_to_ignore: Remove these regexes during step 1 matching
>             """
>             super().__init__(regex_pattern, group_select, fallback)
>             self.ignore_case = ignore_case
>             self.ignore_punctuation = ignore_punctuation
>             self.regexes_to_ignore = regexes_to_ignore
>    ```
> 2. In `lm-evaluation-harness/lm_eval/tasks/bbh/fewshot/_fewshot_template_yaml`, add:
>    ```yaml
>    filter_list:
>      - name: "strict-match"
>        filter:
>          - function: "take_first"
>      - name: "flexible-extract"
>        filter:
>          - function: !function utils.MultiChoiceRegexFilter
>            group_select: 0
>            regex_pattern: "^\\s*(.+?)(?=(\\n+|$))"
>            ignore_case: true
>            ignore_punctuation: true
>          - function: "take_first"
>    ```
> 3. Run the `lm_eval` command. Example:
>    ```
>    lm_eval --model GaC --tasks bbh_fewshot --batch_size 1 --num_fewshot 3
>    ```
> 
> Feel free to reach out if you have any questions!

thank you！
